# -*- coding: utf-8 -*-
"""WebScrapping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRlO57poLiR40FVwkTGg4enfkqYHpYel
"""

import requests
from bs4 import BeautifulSoup

URL='https://codegnan.com/'

page=requests.get(URL)

page.status_code

htmlCode=page.text
print(htmlCode)

soup=BeautifulSoup(htmlCode,'html.parser')
print(soup)

title=soup.title.text
print("Website Title:",title)

headings=soup.find_all('h3')
for heading in headings:
    print(heading.text.strip())

links=soup('a')
for link in links[:10]:
  print(link.get('href'))

images=soup.find_all('img')
for image in images[:10]:
  print(image.get('src'))

desc=soup.find("meta",attrs={'name':'description'})
if desc:
  print("Description:")
  print(desc.get('content'))

for tag in soup.find_all():
  if tag.get("class"):
    print(tag.get("class"))

logo=soup.find("img")
print(logo.get("src"))

og_title=soup.find("meta",property="og:title")
print(og_title["content"])

og_image=soup.find("meta",property="og:image")
print(og_image["content"])

menus = soup.find_all("li")
for menu in menus[:20]:
  print(menu.text.strip())

paragraphs=soup.find_all('p')
for p in paragraphs[:10]:
  print(p.text.strip())

buttons=soup.find_all('button')
for button in buttons[:10]:
  print(button.text.strip())